services:
  - type: web
    name: depth-estimation-backend
    env: python
    repo: https://github.com/kanalia7355/OC_display.git
    branch: master
    rootDir: backend
    buildCommand: chmod +x render_build.sh && ./render_build.sh
    startCommand: python startup.py
    plan: starter
    region: oregon
    autoDeploy: true
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: MODEL_CACHE_DIR
        value: ./models
      - key: TEMP_DIR
        value: ./temp
      - key: PYTHONPATH
        value: .
    healthCheckPath: /health
    
  # オプション: PostgreSQL データベース (将来の拡張用)
  # - type: pgsql
  #   name: depth-app-db
  #   databaseName: depth_app
  #   user: depth_user
  #   plan: starter