services:
  - type: web
    name: depth-estimation-backend
    env: python
    repo: https://github.com/TK561/OC.git
    branch: master
    rootDir: backend
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python run_server.py
    plan: starter
    region: frankfurt
    autoDeploy: true
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: MODEL_CACHE_DIR
        value: /opt/render/project/src/models
      - key: TEMP_DIR
        value: /opt/render/project/src/temp
      - key: PYTHONPATH
        value: /opt/render/project/src
    healthCheckPath: /health
    
  # オプション: PostgreSQL データベース (将来の拡張用)
  # - type: pgsql
  #   name: depth-app-db
  #   databaseName: depth_app
  #   user: depth_user
  #   plan: starter