[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.virtualenv", "libGL", "glib"]

[phases.install]
cmd = "pip install --no-cache-dir -r requirements.txt"

[start]
cmd = "python app.py"

[variables]
PYTHONUNBUFFERED = "1"